In [2]:
import numpy as np
from sklearn.preprocessing import StandardScaler

# 假設我們有一個數據集 X
X = np.array([[2.5, 2.4],
              [0.5, 0.7],
              [2.2, 2.9],
              [1.9, 2.2],
              [3.1, 3.0],
              [2.3, 2.7],
              [2, 1.6],
              [1, 1.1],
              [1.5, 1.6],
              [1.1, 0.9]])

# 步驟 1：標準化數據
X_std = StandardScaler().fit_transform(X)

# 步驟 2：計算協方差矩陣
cov_matrix = np.cov(X_std.T)

# 步驟 3：計算特徵值和特徵向量
eig_vals, eig_vecs = np.linalg.eig(cov_matrix)

# 步驟 4：排序特徵值並選擇前 k 個特徵向量（假設我們選擇 k=1）
eig_pairs = [(np.abs(eig_vals[i]), eig_vecs[:,i]) for i in range(len(eig_vals))]
eig_pairs.sort(key=lambda x: x[0], reverse=True)
W = eig_pairs[0][1].reshape(-1, 1)

# 步驟 5：構建投影矩陣 W
# 步驟 6：將原始數據集 X 轉換為 k 維特徵子空間 Y
Y = X_std.dot(W)

print("原始數據集 X：\n", X)
print("標準化後的數據集 X_std：\n", X_std)



原始數據集 X：
 [[2.5 2.4]
 [0.5 0.7]
 [2.2 2.9]
 [1.9 2.2]
 [3.1 3. ]
 [2.3 2.7]
 [2.  1.6]
 [1.  1.1]
 [1.5 1.6]
 [1.1 0.9]]
標準化後的數據集 X_std：
 [[ 0.92627881  0.61016865]
 [-1.7585873  -1.506743  ]
 [ 0.52354889  1.23278973]
 [ 0.12081898  0.36112022]
 [ 1.73173864  1.35731394]
 [ 0.6577922   0.9837413 ]
 [ 0.25506228 -0.38602507]
 [-1.08737078 -1.00864614]
 [-0.41615425 -0.38602507]
 [-0.95312747 -1.25769457]]


In [3]:
print("協方差矩陣：\n", cov_matrix)


協方差矩陣：
 [[1.11111111 1.0288103 ]
 [1.0288103  1.11111111]]


In [4]:
print("特徵值：\n", eig_vals)


特徵值：
 [2.13992141 0.08230081]


In [5]:
print("特徵向量：\n", eig_vecs)


特徵向量：
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [6]:
print("投影矩陣 W：\n", W)


投影矩陣 W：
 [[0.70710678]
 [0.70710678]]


In [7]:

print("降維後的特徵子空間 Y：\n", Y)

降維後的特徵子空間 Y：
 [[ 1.08643242]
 [-2.3089372 ]
 [ 1.24191895]
 [ 0.34078247]
 [ 2.18429003]
 [ 1.16073946]
 [-0.09260467]
 [-1.48210777]
 [-0.56722643]
 [-1.56328726]]
